name: Check the client

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  check_client:
    name: Testing&Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Get access to files ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install dependenciesğŸ”§
        run: yarn install --frozen-lockfile

      - name: Run Test ğŸ”¨
        run: yarn test

      - name: Lint code
        run: yarn lint
